#!/usr/bin/env bash
# scripts/workspace-init.sh
# Interactive setup wizard for a fresh AI Workspace clone.
#
# Usage:
#   ./scripts/workspace-init.sh

set -euo pipefail

WORKSPACE_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# ── colors ────────────────────────────────────────────────────────────────────
_color() { [[ -t 1 ]] && printf '\033[%sm%s\033[0m' "$1" "$2" || printf '%s' "$2"; }
blue()   { _color "1;34" "$*"; echo; }
green()  { _color "1;32" "$*"; echo; }
yellow() { _color "1;33" "$*"; echo; }
bold()   { _color "1;37" "$*"; echo; }
dim()    { _color "0;37" "$*"; echo; }

ask() {
  # ask <prompt> <default>
  local prompt="${1}" default="${2:-}"
  if [[ -n "${default}" ]]; then
    printf '%s [%s]: ' "${prompt}" "${default}"
  else
    printf '%s: ' "${prompt}"
  fi
  read -r answer
  echo "${answer:-${default}}"
}

echo ""
blue "╔══════════════════════════════════════════════╗"
blue "║      AI Workspace — Setup Wizard             ║"
blue "╚══════════════════════════════════════════════╝"
echo ""
dim "This wizard will create your local config files."
dim "All changes are gitignored — safe to run anytime."
echo ""

# ── Step 1: Make bin scripts executable ──────────────────────────────────────
bold "Step 1/5 — Make bin scripts executable"
chmod +x "${WORKSPACE_ROOT}"/bin/* 2>/dev/null || true
green "  ✓ bin/* executable"
echo ""

# ── Step 2: Create project directories ───────────────────────────────────────
bold "Step 2/5 — Initialize project directories"
mkdir -p "${WORKSPACE_ROOT}/repos" "${WORKSPACE_ROOT}/projects"
green "  ✓ repos/ and projects/ created"
echo ""

# ── Step 3: Configure .workspace.yaml ────────────────────────────────────────
bold "Step 3/5 — Configure local workspace"
workspace_yaml="${WORKSPACE_ROOT}/.workspace.yaml"

if [[ -f "${workspace_yaml}" ]]; then
  yellow "  .workspace.yaml already exists — skipping"
else
  echo ""
  dim "  Let's set up your workspace configuration."
  echo ""

  default_org=$(ask "  Your GitHub org or username" "my-org")
  clone_dir=$(ask "  Where to clone repos (relative to workspace)" "./repos")

  cat > "${workspace_yaml}" << EOF
# Local workspace configuration (gitignored — customize freely)
# Generated by scripts/workspace-init.sh

base_paths:
  default_org: "${default_org}"
  clone_dir: "${clone_dir}"

# Projects directory structure
projects:
  my-org:
    category: my-org
    path: "${clone_dir}/github.com/${default_org}"
    description: My organization's projects
EOF
  green "  ✓ .workspace.yaml created"
fi
echo ""

# ── Step 4: Configure projects.yaml ──────────────────────────────────────────
bold "Step 4/5 — Set up project index"
projects_yaml="${WORKSPACE_ROOT}/projects.yaml"

if [[ -f "${projects_yaml}" ]]; then
  yellow "  projects.yaml already exists — skipping"
else
  cp "${WORKSPACE_ROOT}/projects.yaml.example" "${projects_yaml}"
  green "  ✓ projects.yaml created from example"
  dim "  Edit projects.yaml to add your repos"
fi
echo ""

# ── Step 5: Symlinks for AI tools ─────────────────────────────────────────────
bold "Step 5/5 — Set up AI tool symlinks"

# CLAUDE.md → AGENTS.md
if [[ ! -e "${WORKSPACE_ROOT}/CLAUDE.md" ]]; then
  ln -s AGENTS.md "${WORKSPACE_ROOT}/CLAUDE.md"
  green "  ✓ CLAUDE.md → AGENTS.md"
else
  dim "  CLAUDE.md already exists"
fi

# GEMINI.md → AGENTS.md
if [[ ! -e "${WORKSPACE_ROOT}/GEMINI.md" ]]; then
  ln -s AGENTS.md "${WORKSPACE_ROOT}/GEMINI.md"
  green "  ✓ GEMINI.md → AGENTS.md"
else
  dim "  GEMINI.md already exists"
fi

# .github/copilot-instructions.md → ../AGENTS.md
if [[ ! -e "${WORKSPACE_ROOT}/.github/copilot-instructions.md" ]]; then
  mkdir -p "${WORKSPACE_ROOT}/.github"
  ln -s ../AGENTS.md "${WORKSPACE_ROOT}/.github/copilot-instructions.md"
  green "  ✓ .github/copilot-instructions.md → AGENTS.md"
else
  dim "  .github/copilot-instructions.md already exists"
fi

echo ""
green "╔══════════════════════════════════════════════╗"
green "║  Setup complete!                             ║"
green "╚══════════════════════════════════════════════╝"
echo ""
blue "Next steps:"
echo "  1. Clone your first repo:"
dim "       ./bin/project-indexer clone owner/my-project"
echo ""
echo "  2. Open in your AI tool:"
dim "       opencode   # or: claude / cursor / gemini"
echo ""
echo "  3. (Optional) Queue a background job:"
dim "       ./bin/devcompanion queue my-project --template code-review"
echo ""
echo "  4. Read the docs:"
dim "       docs/METHODOLOGY.md   — How the workspace is designed"
dim "       docs/WORKFLOWS.md     — Common task patterns"
dim "       docs/PERSONAS.md      — Work mode personas"
echo ""
